Squashed 'deps/gdx/' changes from fd0171d3..6ddae6c5
6ddae6c5 Merge commit '151fd42180c6d1be52164cf1ba2a1468790e832f' into develop
151fd421 Squashed 'deps/infra/' changes from 0e4a013c..8ef1b091
d69a044a Update build script
00b24657 [gdal, netcdf] use cmake targets in cmake scripts to fix debug lib locations
5f3d3a7c Merge commit '8317c04bf7e32c5458206113e73ab04fd1901987' into develop
8317c04b Squashed 'deps/vcpkg/' changes from ae224546..c65e1816
25aa336b Add netcdf support
a64d64d2 Fixed warning about ignored const
4fe9c2b6 Squashed 'deps/infra/' changes from af7dc958..0e4a013c
095d72a5 Merge commit '4fe9c2b6a30ff06e204b1b94467640dd652f06e8' into develop
f9d7eb2b Merge branch 'develop' of ssh://git.vito.local:7999/marvin-geodynamix/gdx-core into develop
ee4e517c Inf api changes
67098add inf::gdal api change
a67a12d2 Squashed 'deps/infra/' changes from 1e85c184..af7dc958
a31de598 Merge commit 'a67a12d229f25e8f89f43fa1a8f99c0f297ac052' into develop
9ac7d18f Use tiled mode when writing tiff files
cc7fe459 Fixed read metadata path argument
304d6fbe Use fs::path instead of string in mapping io functions
63057c6b Merge commit 'add5e3014b4553ef1b31d83460f40a0e3f28522e' into develop
add5e301 Squashed 'deps/vcpkg/' changes from 5e4601f5..ae224546
1e71bb87 Support boostrap clean command
01852b64 Fixed clean function
ce1f6853 Merge branch 'develop' of ssh://git.vito.local:7999/marvin-geodynamix/gdx-core into develop
669c5bf2 [gdal] enable iconv on non windows
ad5af37b Merge commit '8d96ff40ccd609d8c7478710a00f240ff2ca2a2b' into develop
8d96ff40 Squashed 'deps/infra/' changes from 4571b9af..1e85c184
2b528123 Merge commit '72170147a52d5399a257e5af285c38b0c0da56da' into develop
72170147 Squashed 'deps/vcpkg/' changes from 211f9aca..5e4601f5
1e55c11e Update bootstrap script
4a70d341 Fixed duplicate bootstrap argparser
6a128f1a reclass modifications
8ddb763b Merge branch 'develop' of ssh://git.vito.local:7999/marvin-geodynamix/gdx-core into develop
fc56cad7 Reclass function that does not return variant
c1528174 Merge commit 'd842ce2375831d86bc842cce3a00ccaf437634ab' into develop
d842ce23 Squashed 'deps/vcpkg/' changes from 211f9aca..a300cb78
977dbfef Merge commit 'da06982f1cb44e4101e0e01d41a7cfe931d5395d' into develop
da06982f Squashed 'deps/infra/' changes from 4571b9af..4770c87e
aa3a7ea5 Enabled the infra tests
8e291b45 [gdal] enable iconv support so gdal is able to convert codepages to utf-8
613c6d63 character set conversion and detection functionality csvreader tha supports reading non utf-8 csv files
a518fa25 Fixed gdaltest
cbff9160 Squashed 'deps/infra/' changes from c3164b75..4571b9af
5ea1088b Merge commit 'cbff9160853e6bbc806c5e438599d79c92dc4290' into develop
da5cd20e inline read_dense_raster
c50ce569 Support reading dense rasters without knowing the type
0aba2710 fixed bug in test code
f5f432d1 Merge branch 'develop' of https://git.vito.be/scm/marvin-geodynamix/gdx-core into develop
eb9491de Squashed 'deps/vcpkg/' changes from 7aed8906..211f9aca
5fe25983 Merge commit 'eb9491def9a6709a525fb4e2af9923f8a438893c' into develop
6dd8e87b Fixed linker errors
1e594889 Fixed warning
3ee763c1 voorbeeld weiss algoritme in gdx (weighted-distribution).  visual studio compiler nu met AVX2 compilatieflag.
1b326af1 Squashed 'deps/infra/' changes from 90366a51..c3164b75
2d2af674 Merge commit '1b326af1c422ba344c40f5a1b9d910da91cac792' into develop
c8feb4e3 Merge commit 'ef77c6b10d63a4ba56c0a3869aefa7df16532064' into develop
ef77c6b1 Squashed 'deps/infra/' changes from 0766ed3e..90366a51
1f34d3ec Fixed test after rename
df00f0d2 colormap algo added
b651bf84 fixed bug in compute_rect_on_map_around function.
154cc13d fixed test because type of result of reclass/reclassi/nreclass became different (but correct) than in reference raster.  (Rastercompare stops if types of rasters are different)
20231546 reclass result type now depends on reclas table result type
fd0c99d6 Fixed filter algorithm compilation error
58fc761f Squashed 'deps/vcpkg/' changes from a24ba6e0..7aed8906
cd224f5f Merge commit '58fc761f27f2ffa786bbfbe5227412748f8dbeec' into develop
c9b37538 Fmt api changes
d2c3c7a9 Squashed 'deps/vcpkg/' changes from 544fb4bc..a24ba6e0
47f6d6d9 Merge commit 'd2c3c7a956155d712cfc1fec033c1bedcbacb410' into develop
6619d4fb Log api change
44cd3b97 Merge commit 'f21e6b623f834f2f986cbcce49361b3a5d322d85' into develop
f21e6b62 Squashed 'deps/infra/' changes from 12c834fa..0766ed3e
cb63487b Wrapper around OGRSpatialRef class as it's destructor is deprecated and causes memory leaks
6f45e99d Change install dir on linux
1bae2ef8 Fixed version number
48ac9b0e Fixed version and installation path

git-subtree-dir: deps/gdx
git-subtree-split: 6ddae6c5995f94e723ea1917d8df5d9b19a11ce3